name: Publish Common Module

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # 최신 코드 가져오기
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      # 버전 가져오기
      - name: Check Version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          tag_prefix: ""
          major_pattern: "major"
          minor_pattern: "feat"
          search_commit_body: true

      # 태그 생성 및 푸쉬
      - name: Push Tag
        run: |
          git tag ${{ steps.semver.outputs.version }}
          git push https://x-access-token:${{ secrets.TOKEN }}@github.com/${{ github.repository }} ${{ steps.semver.outputs.version }}

      # JDK 설치
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 배포(GitHub Packages)
      - name: Build & Publish
        run: ./gradlew publish
        env:
          VERSION: ${{ steps.semver.outputs.version }}
          PACKAGES_URL: ${{ secrets.PACKAGES_URL }}
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}